### ISSUE TITLE
RxTableViewSectionedAnimatedDataSource update cell starange behaviour

### ISSUE THREAD

**Issue by pgawlowski** [RxSwiftCommunity/RxDataSources#295] opened 2019-03-21 14:48 UTC
![Mar-21-2019 15-42-40](https://user-images.githubusercontent.com/9845024/54760265-020ab080-4bf0-11e9-9c2f-08a2a416c100.gif)

I will describe in points what is happenig:
1. Start with loading data.
2. My cells are expandable - click on one cell to present unhide stackView.
3. It animates in a little bit strange way and as you can see it leave strange gaps on the bottom
4. Let's scroll a little bit down
5. Now everythings look perfect!

How to achieve this effect instantly? 
I am cashing cell sizes.
I've tried to disable animations however .none is not working here.

Probably it is somehow connected with prefetching. And on the gif you can see that I scrolled to the very end of array. However I tried the same with much bigger data collection and every single time problem disappears after just a short scroll.

**Comment by mkko** [comment] 2019-03-22 08:41
How do expand the cells? Are you using sections or is this a flat structure? If you could provide reproducible example of this I could try to check it out.

**Comment by pgawlowski** [comment] 2019-03-22 13:42
Those are cells with stackview inside. Expand is happening when I unhide stackView elements.

I figured out that disabling animations with 

> class func setAnimationsEnabled(_ enabled: Bool)

solves the problem. So it has to be connected with insert/reload animation.

**Comment by mkko** [comment] 2019-03-24 12:07
Glad to hear you found a solution.

Without knowing about the implementation it could also be an issue with auto layout. Are you sure the header in the stack view is not recreated for any reason? Based on the animation it looks like one is faded out and another is animated into its place.

**Comment by mkko** [comment] 2019-03-25 08:08
Closing this due to the issue being resolved.

**Closed by mkko** 2019-03-25 08:08 UTC
