### ISSUE TITLE
support custom section headerView

### ISSUE THREAD

**Issue by julesli** [RxSwiftCommunity/RxDataSources#182] opened 2017-10-23 09:26 UTC
we have to use traditional UITableViewDelegate method  to custom  section headerView, we prefer to use like the way of dataSource.configcell closure

**Comment by mzgnr** [comment] 2017-10-23 13:05
`class LiveScoreHeader: UITableViewHeaderFooterView {
    ...
}`

and use func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? delegate method.

**Comment by julesli** [comment] 2017-10-24 10:31
we prefer to use like the way of dataSource.configcell closure
  
self.dataSource.configureSectionHeaderFooter =  { dataSource, tableView, indexPath, item in
            let header =  MyCustomHeader()
            header.title =  item.title
            return header
        }

**Comment by adrianodiasx93** [comment] 2017-11-02 21:20
+1

**Comment by stebaps** [comment] 2017-11-07 17:13
+1 😀

**Comment by pixeldock** [comment] 2017-12-28 08:16
+1

**Comment by qiushuitian** [comment] 2018-01-15 05:52
+1

**Comment by sergdort** [comment] 2018-01-21 11:30
Hi guys, I feel like this is duplicate of #203

**Closed by sergdort** 2018-01-21 11:30 UTC

**Comment by qiushuitian** [comment] 2018-01-27 06:52
what about UICollectionView?

**Comment by sergdort** [comment] 2018-02-03 11:27
There is `configureSupplementaryView` closure [here](https://github.com/RxSwiftCommunity/RxDataSources/blob/master/Sources/RxDataSources/CollectionViewSectionedDataSource.swift#L138)
