### ISSUE TITLE
Occasionally getting a crash when using RxCollectionViewSectionedAnimatedDataSource

### ISSUE THREAD

**Issue by avdwerff** [RxSwiftCommunity/RxDataSources#60] opened 2016-08-31 10:42 UTC
Randomly I'm facing crashes when using RxCollectionViewSectionedAnimatedDataSource, or at least when using the non animated flavour is seems to be stable. When a crash occurs the stack trace, reports me a 
**Fatal Exception: NSInternalInconsistencyException** 
with a message: 
_Invalid update: invalid number of sections. The number of sections contained in the collection view after the update (3) must be equal to the number of sections contained in the collection view before the update (3), plus or minus the number of sections inserted or deleted (1 inserted, 0 deleted)._
It seems to happen after UI+SectionedViewType.swift line 98 and will crash somewhere in **UICollectionView _performBatchUpdates:completion:invalidationContext:** 
This does not happen when using a RxCollectionViewSectionedReloadDataSource, so my question is more if this is a known issue and if anybody facing the same kind of issue resolved it, any help is appreciated.  I'm using RxDatasource version 0.6.2.

**Comment by kzaher** [comment] 2016-08-31 13:11
Hi @avdwerff ,

Could you please try latest 0.9 version?

It would be great if you could get us a self contained example that crashes the app.

**Comment by TheAdamBorek** [comment] 2016-09-01 09:13
Hi guys,
I've just figured the cause of my crash in `RxCollectionViewSectionedAnimatedDataSource`. I had a similar scenario, that `UITableView` calls `cellForRowAtIndexPath:` after calling `[UITableView endUpdates]` with indexPath which was out of bounds of current datasource. 

It seems the reason of the crash is ... iOS9 :(. I've found [this stackoverflow issue](http://stackoverflow.com/questions/34443185/uitableview-crashes-on-ios-9-when-endupdates-is-called-with-exc-bad-access) and I tested my scenario on iOS10. It doesn't crash at all

@avdwerff Try running it on different version of iOS

**Comment by avdwerff** [comment] 2016-09-01 10:46
@TheAdamBorek thanks for the tip, I will try! I figured that it happens when the datasource updates , while the collectionview is still in an animation from a previous update.

**Comment by avdwerff** [comment] 2016-09-01 10:51
@kzaher I will check if I can reproduce the problem in a self contained example, unfortunately I can't share the code from the project, since the client is not allowing it. For now I'm ok with using RxCollectionViewSectionedReloadDataSource and until now the crash does not seem to happen anymore.

**Comment by kzaher** [comment] 2016-09-01 14:39
@avdwerff yeah, sure.

If you can create a repro case, that would be great, otherwise I've hit a dead end and not sure what can I do :)

I'm also shipping this code, and I'm sure other people are also, so I would like to understand what was the exact problem you've encountered on iOS 9, and can we do something to solve it in a trivial way.

**Comment by kzaher** [comment] 2016-09-02 13:00
@avdwerff oh, yeah, sorry. I haven't seen you've mentioned collection view, and not table view.

I've noticed that collection view has a lot of bugs in partial updates code. You can replicate that easily if you perform **collection view** animated updates fast. If you perform those same updates slower or on table views, they will work.

¯\\\_(ツ)\_/¯

**Comment by avdwerff** [comment] 2016-09-07 19:46
@kzaher so then we know what the problem is I guess, it was about fast partial animated updates in nested collection views. And indeed the crash did not occur when some network call took longer responsible for updating the main collectionview.

**Comment by kzaher** [comment] 2016-09-11 01:07
I've added throttle operator inside `RxCollectionViewSectionedAnimatedDataSource`. It's a silly solution to this problem, but seems to be working for now.

This will be released with Swift 3.0 version of RxDataSources though.

**Comment by shams-ahmed** [comment] 2017-04-23 10:15
Hi, am sure I get the same issue:

iOS 10.3
RxDataSources Version: 1.0.3

Crash logs:
```
2017-04-23 11:04:29.812701+0100 APP[1976:576981] *** Assertion failure in -[APP.NearMeCollectionView _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3600.8.1/UICollectionView.m:5781
2017-04-23 11:04:29.813102+0100 APP[1976:576981] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (95) must be equal to the number of items contained in that section before the update (95), plus or minus the number of items inserted or deleted from that section (95 inserted, 0 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'
*** First throw call stack:
(0x190a26fe0 0x18f488538 0x190a26eb4 0x1914be720 0x197462060 0x197465b34 0x197465e14 0x197465c74 0x197465bf8 0x196d2e400 0x100df8f58 0x100dea7c0 0x100deab44 0x100c58910 0x100dea248 0x100de9e64 0x100de9fb4 0x100f7eeac 0x100f7f690 0x100ee5678 0x100f84efc 0x100f8544c 0x100fccf00 0x100fee928 0x100feda2c 0x100fef300 0x100fe078c 0x100fed438 0x100fef26c 0x100f8339c 0x100f83b88 0x100f4bb3c 0x100f38138 0x101b7da50 0x101b7da10 0x101b82b78 0x1909d50c8 0x1909d2ce4 0x190902da4 0x19236c074 0x196bbd364 0x1000f9d6c 0x18f91159c)
libc++abi.dylib: terminating with uncaught exception of type NSException
(Recorded stack frame) 
```

**Comment by shams-ahmed** [comment] 2017-04-27 13:08
Going to close ticket, my issue was due to timing of binding my models... long story short do bind to models at the end

**Closed by shams-ahmed** 2017-04-27 13:08 UTC

**Comment by mashe** [comment] 2019-04-02 11:29
Hello everyone,

I think I have found the root of the issue. It lays in usage of `performBatchUpdates:completion:` method. According to [Apple Documentation](https://developer.apple.com/documentation/uikit/uicollectionview/1618045-performbatchupdates?language=objc):

> If the collection view's layout is not up to date before you call this method, a reload may occur. To avoid problems, you should update your data model **inside** the updates block or ensure the layout is updated before you call performBatchUpdates:completion:.

while RxCollectionViewSectionedAnimatedDataSource updates data model outside the block, what may lead to inconsistency of layout and crash. And actually does sometimes.

```
RxCollectionViewSectionedAnimatedDataSource.swift:91

                case .animated:
                    for difference in differences {
                        dataSource.setSections(difference.finalSections)

                        collectionView.performBatchUpdates(difference, animationConfiguration: self.animationConfiguration)
                    }
                case .reload:

```

**Comment by kzaher** [comment] 2019-04-02 18:05
@mashe can you do a pull request?

**Comment by mashe** [comment] 2019-04-03 15:55
@kzaher gonna make it this week

**Comment by mashe** [comment] 2019-04-07 11:34
@kzaher here it is
