### ISSUE TITLE
how to config header view of different for UITableView?

### ISSUE THREAD

**Issue by qiushuitian** [RxSwiftCommunity/RxDataSources#226] opened 2018-04-09 08:27 UTC
config cell can using like this:
```
        self.dataSource = RxTableViewSectionedReloadDataSource<SectionOfCurrencyRecord>(
            configureCell: { (ds, tv, indexPath, item) -> UITableViewCell in
                let cell = tv.dequeue(Reusable.currencyRecordCell, for: indexPath)
                cell.itemData.value = item
                return cell
            }
        )
```

so what about config the header view ? Not every header of section just a title string.

**Comment by foxware00** [comment] 2018-04-12 15:20
Also curious of the best way to achieve this

**Comment by Vkt0r** [comment] 2018-04-12 16:08
I think there is nothing in the library to achieve this directly yet. But you can achieve it using the normal `UITableViewDelegate` methods:

* `func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView?`
* `func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat`

Let's say I modify the example `Example4_DifferentSectionAndItemTypes` to achieve it. I want to use a 
`viewForHeaderInSection ` only in the section 2 and keep the rest using the title.

```swift
extension MultipleSectionModelViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        guard section == 2 else { return nil }
        let frame = CGRect(x: 0, y: 0, width: view.bounds.width, height: 42)
        let headerView = UIView(frame: frame)
        headerView.backgroundColor = UIColor.darkGray
        return headerView
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 40
    }
}
```

Another important thing to do is you need to set the delegate explicitly or implicitly using Interface Builder, up to you, explicitly you can do it like this in the `viewDidLoad `:

```swift
tableView
  .rx.setDelegate(self)
  .disposed(by: disposeBag)
```

That should be enough 😅.

**Comment by foxware00** [comment] 2018-04-13 08:47
Perfect thank you worked like a treat

**Comment by Vkt0r** [comment] 2018-04-13 14:16
@foxware00 Yes it overrides the default `tableView(_:titleForHeaderInSection:)`, but I think that is the expected behavior in the `UITableView`, it doesn't have anything to do with the library.  So we can close this.

**Comment by yoshalevi2** [comment] 2018-06-01 05:16
How can I use the delegate function viewForHeaderInSection, and still set the title using the RxTableViewSectionedAnimatedDataSource object ? 
U think this issue does related to the library, because "titleForHeaderInSection" is overridden in this case, so what can I do to modify the section UI and still use the library's datasource?

**Comment by qiushuitian** [comment] 2018-06-12 09:15
![image](https://user-images.githubusercontent.com/3318393/41281172-57dfad0a-6e63-11e8-9d32-43a4fb575a64.png)

@Vkt0r @floskel  The solution above does't slove my problem.

1. using the delegate may config the headView cell. but It can't config association the data.  I want to config each section with different head view.  Using tableview deletage I can't get anything about the dataSource .

2. Mabe the RxDataSouce only care of the tableview's datasource. but many ocasions we have to do the work with delegate. Only datasource seems a half work of UITableView.

**Comment by Vkt0r** [comment] 2018-06-14 15:29
@qiushuitian You can get the `dataSource` elements from the `tableView(_: viewForHeaderInSection:)`! You only need to set the `dataSource` as a property in your `UIViewController` and you can get the elements in your `Section` whatever it is.  

I modified the `MultipleSectionModelViewController` to support multiple `headerViews` regarding the `dataSource` and using the information in the `Section` defined.

```swift
extension MultipleSectionModelViewController: UITableViewDelegate {
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        
        let frame = CGRect(x: 0, y: 0, width: view.bounds.width, height: 42)
        let headerView = UIView(frame: frame)
        headerView.backgroundColor = .darkGray
        
        let sectionLabel = UILabel(frame: frame)

        // get the title from the dataSource
        sectionLabel.text = dataSource[section].title

        sectionLabel.textColor = .white
        headerView.addSubview(sectionLabel)
        headerView.backgroundColor = section == 2 ? .darkGray : .black
    
        return headerView
    }
    
    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 40
    }
}
```

And I defined before the `dataSource` as a property in the `UIViewController` like the following code:

```swift
class MultipleSectionModelViewController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!
    let disposeBag = DisposeBag()
    
    var dataSource: RxTableViewSectionedReloadDataSource<MultipleSectionModel>!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let sections: [MultipleSectionModel] = [
            .ImageProvidableSection(title: "Section 1",
                items: [.ImageSectionItem(image: UIImage(named: "settings")!, title: "General")]),
            .ToggleableSection(title: "Section 2",
                items: [.ToggleableSectionItem(title: "On", enabled: true)]),
            .StepperableSection(title: "Section 3",
                items: [.StepperSectionItem(title: "1")])
        ]
        
        dataSource = MultipleSectionModelViewController.dataSource()
        
        Observable.just(sections)
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
        
        tableView
            .rx.setDelegate(self)
            .disposed(by: disposeBag)
    }
}
```

And if you see the complete code for the `MultipleSectionModelViewController` in the examples you can see you can even get any information you want from the `dataSource`, for example see below how a `switch` statement is used to match sections:

```swift
extension MultipleSectionModelViewController {
    static func dataSource() -> RxTableViewSectionedReloadDataSource<MultipleSectionModel> {
        return RxTableViewSectionedReloadDataSource<MultipleSectionModel>(
            configureCell: { (dataSource, table, idxPath, _) in
                switch dataSource[idxPath] {
                case let .ImageSectionItem(image, title):
                    let cell: ImageTitleTableViewCell = table.dequeueReusableCell(forIndexPath: idxPath)
                    cell.titleLabel.text = title
                    cell.cellImageView.image = image

                    return cell
                case let .StepperSectionItem(title):
                    let cell: TitleSteperTableViewCell = table.dequeueReusableCell(forIndexPath: idxPath)
                    cell.titleLabel.text = title

                    return cell
                case let .ToggleableSectionItem(title, enabled):
                    let cell: TitleSwitchTableViewCell = table.dequeueReusableCell(forIndexPath: idxPath)
                    cell.switchControl.isOn = enabled
                    cell.titleLabel.text = title

                    return cell
                }
            }
        )
    }
}
```

**Comment by freak4pc** [comment] 2018-08-24 16:39
This is out of scope for the library - since a header view isn't part of the data source.

What would be best is to forward the delegate (e.g. `tableView.rx.setDelegate(self)`) and then use the proper delegate method to provide your custom view.

**Closed by freak4pc** 2018-08-24 16:39 UTC
Labels: question

**Comment by Sadmansamee** [comment] 2020-05-15 04:47
@Vkt0r I followed your code but 
`    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
`
isn't getting called at all.what might be the reason?

**Comment by realityworks** [comment] 2020-11-27 16:03
> @Vkt0r I followed your code but
> ` func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {`
> isn't getting called at all.what might be the reason?

A bit late, but have you tried :```

tableView
            .rx.setDelegate(self)
            .disposed(by: disposeBag)
```

**Comment by pratik644** [comment] 2020-12-23 17:44
Not the best/cleanest solution out there but it might help someone looking for a quick hack. I had run into a situation where the section title included information about the number of cells so it had to come from the dataSource but i also wanted to customize the headerView and its content. My customizations were limited to changing the default textLabel color, view background color and adding a bottom line so your milage may vary but below is how I did it:

`
let dataSource = RxTableViewSectionedReloadDataSource<MySection> { (_, tableView, _, item) -> UITableViewCell in
            let cell = tableView.dequeueReusableCell(withIdentifier: MyCell.reuseIdentifier) as? MyCell ?? MyCell()
            cell.configure(item: item)
            return cell
        }
        
        dataSource.titleForHeaderInSection = { dataSource, index in
            return dataSource.sectionModels[index].headerText
        }
        
        _ = Observable.just(sections)
            .takeUntil(tableView.rx.deallocated)
            .bind(to: tableView.rx.items(dataSource: dataSource))
`

Then listen for the `willDisplayHeaderView:forSection` event and customize the headerView as you desire:

`
_ = tableView.rx.delegate.methodInvoked(#selector(tableView.delegate?.tableView(_:willDisplayHeaderView:forSection:)))
            .takeUntil(tableView.rx.deallocated)
            .subscribe(onNext: { event in
                guard let headerView = event[1] as? UITableViewHeaderFooterView else {
                    return
                }
                for view in headerView.subviews {
                    view.backgroundColor = .white
                }
                headerView.textLabel?.attributedText = headerView.textLabel?.text?.attributedString(textStyle: .b3, alignment: .left, textColor: .navy)
                
                let separatorLine = UIView(frame: CGRect(x: 0, y: headerView.bounds.height - 1, width: headerView.frame.width, height: 1))
                separatorLine.backgroundColor = .veryLightBlue
                headerView.addSubview(separatorLine)
            })
            `
