### ISSUE TITLE
Supplementary View Factory

### ISSUE THREAD

**Issue by Gdev82** [RxSwiftCommunity/RxDataSources#127] opened 2017-05-11 16:05 UTC
First of all thank you for this great library. I just started using it a couple of weeks ago, and I stumbled upon an issue. The issue is when using a collection view controller not instantiated from storyboard (as shown in the examples). More precisely when I register a UICollectionReusableView in code as shown below

`collectionView.register(MyReusableView.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "test")`

the code block for the supplementary view factory never gets called. The example I am using is shown here

```
datasource.supplementaryViewFactory = {(ds,cv,kind,index) in
            let cell = cv.dequeueReusableSupplementaryView(ofKind: kind, withReuseIdentifier: "test", for: index) as! TestReusableView
            
            cell.value?.text = "sample text"
            
            return cell
        }
```
If I move delete my code and put the reusable view in the storyboard as part of the collection view, and give the identifier there for my class, it works as expected. 

Is this by design, am I doing something wrong in my code?

Thank you in advance for your help.

George

**Comment by kzaher** [comment] 2017-05-27 22:14
Hi @Gdev82 ,

I think we are only forwarding call to data source. We aren't doing anything special there.

**Comment by Gdev82** [comment] 2017-05-28 18:15
Hi @kzaher ,

I tried a very simple example as shown above and it is not getting called. 

Also, I downloaded the samples fro the GitHub repository and removed the reusable header view from the collection view in the storyboard, and tried to do the registration in code just to reproduce the issue I was facing, and the same thing happens. Which is not the case for regular collection view cells.

Not sure why this is happening, very strange behaviour. 

For now I will use the storyboard to register my reusable view for the collection view, but if you have the opportunity to reproduce this, it is not going to take much of your time, please do so, and let me know the outcome. I would like to know if it can be solved or not. 

Maybe this has to do with some behaviour of the language and not RxSwift producing this strange issue. It would be easier to register the reusable views in code as I do with the rest of the cells.

Thank you.

George

**Comment by lamson** [comment] 2017-05-31 01:10
I ran into the same issue. @Gdev82, thanks to your description, I finally got a workaround for my problem. Agree that this is a very strange behavior. I also have a custom `UICollectionViewFlowLayout`, which made the issue worst... 

I ended up creating a a blank view controller and register the header via the storyboard, also having to remove my custom layout to make it work.

**Comment by VyNguyen0102** [comment] 2017-06-10 06:21
I have same issue. (RxDataSource ver 1.0.3).
Function supplementaryViewFactory will not be called if you register sectionCellNib by code.
Because of some reason i can't using StoryBoard in my project to make it work.
I'm stuck, please help.

**Comment by VyNguyen0102** [comment] 2017-06-22 09:36
I see that Function supplementaryViewFactory also not called if you set CollectionViewLayout by code
`collectionView.setCollectionViewLayout(layout, animated: true)`

**Comment by sergdort** [comment] 2017-06-24 15:08
Hey, guys I was able to reproduce it only if a collection view layout does not return appropriate size for supplementary view.

Please make sure you set size to collection view layout or return appropriate size from `UICollectionViewFlowLayoutDelegate`

I'm gonna close it for now, feel free to reopen it, if you still have an issues

**Closed by sergdort** 2017-06-24 15:08 UTC

**Comment by VyNguyen0102** [comment] 2017-06-24 15:57
hi @sergdort 
I think problem is not about the
`UICollectionViewFlowLayoutDelegate `
Could you please try to register Supplementary View by code instead of include on Storyboard
I see that @Gdev82, @Maximo (issue #139) and me use same method to register Supplementary view

Code of @Gdev82 
`collectionView.register(MyReusableView.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "test")`

Code of @Maximo
`collectionView.register(MyCollectionHeader.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "Section")`
        
Thanks for your support.

**Comment by chinaysun** [comment] 2017-10-24 01:42
Hi,

Please check if you set up the delegate to the collection view? And implement the function 
 collectionView(_ collectionView: ... referenceSizeForHeaderInSection ...) -> CGSize to set the size of header?

Cheers

**Comment by gityuency** [comment] 2018-03-16 07:51
Finally , I made my CollectionView Header showed.   It's very interesting. Just like this below ↓
` let layout =  UICollectionViewFlowLayout()
        layout.headerReferenceSize = CGSize(width: 100, height: 100)
        collectionView =  UICollectionView(frame: CGRect(x: 0, y: 100, width: 200, height: 400), collectionViewLayout: layout)
         collectionView.register(MyHeader.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "header")`
       
then, the closure of "ConfigureSupplementaryView" worked.

🙅 I don't need this ↓
extension ViewController: UICollectionViewDelegateFlowLayout { 
 // ......
}

Other settings just as Demo do.

Deep Dark Fantasies ♂

**Comment by PurpleShrek** [comment] 2022-07-06 18:54
> Finally , I made my CollectionView Header showed. It's very interesting. Just like this below ↓ ` let layout = UICollectionViewFlowLayout() layout.headerReferenceSize = CGSize(width: 100, height: 100) collectionView = UICollectionView(frame: CGRect(x: 0, y: 100, width: 200, height: 400), collectionViewLayout: layout) collectionView.register(MyHeader.self, forSupplementaryViewOfKind: UICollectionElementKindSectionHeader, withReuseIdentifier: "header")`
> 
> then, the closure of "ConfigureSupplementaryView" worked.
> 
> 🙅 I don't need this ↓ extension ViewController: UICollectionViewDelegateFlowLayout { // ...... }
> 
> Other settings just as Demo do.
> 
> Deep Dark Fantasies ♂

the whole point was that it was necessary to set the size of the header in the 'layout' in advance:
`layout.headerReferenceSize = CGSize(width: 100, height: 100)`
